# Generated by Django 3.0.8 on 2020-08-08 12:33

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(upload_to=gallery.models.upload_path),
        ),
    ]
